fixed typos causing compilation problems
Previous errors:
make[1]: Entering directory `/home/admin/dg_epool/Digitizers/gui'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/admin/dg_epool/Digitizers/gui'
make[1]: Entering directory `/home/admin/dg_epool/Digitizers/core'
g++ -g --std=c++11  -c -m64 -pipe -Wshadow -W -Wall -Woverloaded-virtual -fsigned-char -fno-common -I./ -I../gui -I../digitizer/CAEN5740 -I../digitizer/SIM ADataSave2.cpp -pthread -std=c++11 -Wno-deprecated-declarations -m64 -I/usr/include/root -o ADataSave2.o
In file included from ADataSave2.cpp:18:0:
ADataSave2.h:53:19: error: expected ?;? at end of member declaration
  Bool_t   TimerDone()
                   ^
ADataSave2.cpp: In constructor ?ADataSave2::ADataSave2(bool)?:
ADataSave2.cpp:78:40: error: invalid use of member function (did you forget the ?()? ?)
  aTimer->Start(aManager->GetFileTime * 1000);
                                        ^
ADataSave2.cpp: At global scope:
ADataSave2.cpp:30:1: warning: unused parameter ?a? [-Wunused-parameter]
 ADataSave2::ADataSave2(bool a)
 ^
ADataSave2.cpp:233:8: error: ?DataSave2? has not been declared
 Bool_t DataSave2::TimerDone(){
        ^
ADataSave2.cpp: In function ?Bool_t TimerDone()?:
ADataSave2.cpp:236:3: error: ?mSaveTimeout? was not declared in this scope
   mSaveTimeout = 1;
   ^
make[1]: *** [ADataSave2.o] Error 1
make[1]: Leaving directory `/home/admin/dg_epool/Digitizers/core'
make: *** [core] Error 2